import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} p-10`}>
        <nav>
          Navigation |{" "}
          <Link className="hover:text-red-400" href="/">
            Go Home
          </Link>{" "}
        </nav>
        {children}
      </body>
    </html>
  );
}
